
import logging
from typing import List, Tuple
# Import from local modules
from Modules.Universal_Vectorizer.quantizer import QuantizedLayer

# Logging setup
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("SVGComposer")

class SVGComposer:
    """
    Assembles SVG vector files from quantized layers and path data.
    """
    
    def __init__(self, width: int, height: int):
        self.width = width
        self.height = height
        self.layers = []
        
    def add_layer(self, layer_data: QuantizedLayer, paths: List[str]):
        """
        Adds a processed layer to the composition.
        """
        self.layers.append({
            "meta": layer_data,
            "paths": paths
        })
        
    def save(self, filepath: str):
        """
        Writes the final SVG file to disk.
        """
        svg_content = [
            '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
            f'<svg width="{self.width}" height="{self.height}" viewBox="0 0 {self.width} {self.height}"',
            '     xmlns="http://www.w3.org/2000/svg" version="1.1">',
            f'<!-- Generated by ONI Universal Vectorizer v25 -->'
        ]
        
        # Sort layers? Usually darkest/largest first (background) -> smallest (foreground)
        # Assuming the caller (main logic) adds them in correct order.
        # Inkscape typically stacks from bottom up.
        
        for idx, layer in enumerate(self.layers):
            meta = layer["meta"]
            paths = layer["paths"]
            hex_color = meta.color_hex
            
            # Create a group for this color layer
            # Useful for easy selection in Corel/Illustrator
            svg_content.append(f'  <g id="Layer_{idx}_{hex_color[1:]}" fill="{hex_color}" stroke="none">')
            
            for path_d in paths:
                svg_content.append(f'    <path d="{path_d}" />')
                
            svg_content.append('  </g>')
            
        svg_content.append('</svg>')
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(svg_content))
            
        logger.info(f"Saved SVG to {filepath} with {len(self.layers)} layers.")

if __name__ == "__main__":
    pass
