import logging
import time
import re
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional, Tuple
from .config import logger
from .utils import parse_timestamp, format_duration, ProgressTracker

class KnowledgeGenerator:
    def __init__(self, video_dir: Path, video_path: Path, title: str, 
                 frame_paths: List[Path], annotations: List[Dict], 
                 transcript_lines: List[str], interval: int, language: str,
                 stats: Dict, version: str):
        self.video_dir = video_dir
        self.video_path = video_path
        self.title = title
        self.frame_paths = frame_paths
        self.annotations = annotations
        self.transcript_lines = transcript_lines
        self.interval = interval
        self.language = language
        self.stats = stats
        self.version = version

    def generate_knowledge_base(self) -> Path:
        """Generates consolidated Markdown document"""
        logger.info("📚 STEP 5: Generating Knowledge Base...")
        
        analyses = []
        index_entries = []
        
        progress = ProgressTracker(len(self.frame_paths), "Generating")
        
        for i, frame_path in enumerate(self.frame_paths):
            annotation = self.annotations[i] if i < len(self.annotations) else None
            analysis, section_id = self.analyze_frame(i, frame_path, annotation)
            analyses.append(analysis)
            
            ts = parse_timestamp(frame_path.name)
            ts_str = f"{ts[0]:02d}m{ts[1]:02d}s" if ts else "??:??"
            index_entries.append(f"- [{ts_str}](#{section_id}) - Frame {i}")
            
            progress.update()
        
        progress.close()
        
        summary = self._generate_executive_summary()
        kb_path = self.video_dir / "KNOWLEDGE_BASE.md"
        elapsed = time.time() - self.stats["start_time"] if self.stats.get("start_time") else 0
        
        header = f"""# 🎓 KNOWLEDGE BASE: {self.title}

> **Generated automatically** by Video Knowledge Generator V{self.version}
> 
> | Info | Value |
> |------------|-------|
> | 📅 Date | {datetime.now().strftime('%Y-%m-%d %H:%M')} |
> | 🎬 Video | `{self.video_path.name}` |
> | 🖼️ Frames | {len(self.frame_paths)} |
> | ⏱️ Interval | {self.interval}s |
> | 🌐 Language | {self.language.upper()} |
> | ⚙️ Processing Time | {format_duration(elapsed)} |

---

## 📊 EXECUTIVE SUMMARY

{summary}

---

## 🔑 INDEX

{chr(10).join(index_entries)}

---

## 🚀 HOW TO USE

1. **Navigate the index** by clicking timestamps
2. **View annotated images** with UI detection
3. **Read transcript** for the exact moment
4. **Analyze context** and inferred action

---

# 📖 FRAME-BY-FRAME ANALYSIS

"""
        
        with open(kb_path, 'w', encoding='utf-8') as f:
            f.write(header)
            f.write(''.join(analyses))
            f.write(f"\n\n---\n\n## 📈 FINAL STATISTICS\n\n")
            f.write(f"| Metric | Value |\n|---------|-------|\n")
            f.write(f"| Analyzed Frames | {len(self.frame_paths)} |\n")
            f.write(f"| Successful Annotations | {self.stats.get('frames_annotated', 0)} |\n")
            f.write(f"| Failed | {self.stats.get('frames_failed', 0)} |\n")
            f.write(f"| UI Elements Detected | {self.stats.get('total_elements', 0)} |\n")
            f.write(f"| Transcript Lines | {len(self.transcript_lines)} |\n")
            f.write(f"\n---\n\n*Generated by Video Knowledge Generator V{self.version} - ONI System*\n")
        
        logger.info(f"   ✅ Knowledge Base: {kb_path.name}")
        return kb_path

    def analyze_frame(self, idx: int, frame_path: Path, 
                     annotation: Optional[Dict]) -> Tuple[str, str]:
        """Generates structured analysis of a frame"""
        
        ts = parse_timestamp(frame_path.name)
        if ts:
            minutes, seconds = ts
            ts_str = f"{minutes:02d}m{seconds:02d}s"
        else:
            ts_str = "??m??s"
            minutes, seconds = 0, 0
        
        if annotation:
            total_elements = annotation.get('total_elements', 0)
            key_buttons = annotation.get('key_buttons', [])
            num_buttons = len(key_buttons)
            button_list = ', '.join([b.get('text', 'N/A') 
                                    for b in key_buttons[:10]]) if key_buttons else "None detected"
        else:
            total_elements = 0
            num_buttons = 0
            button_list = "⚠️ Analysis not available"
        
        transcript = self.get_transcript_segment(minutes, seconds)
        annotated_name = f"{frame_path.stem}_annotated.png"
        section_id = f"frame-{idx}"
        
        context = self._infer_context(annotation, transcript)
        action = self._infer_action(annotation, transcript)
        
        md = f"""
---

<a id="{section_id}"></a>
## 🔍 FRAME {idx} • {ts_str}

### 🖼️ VISUAL ANALYSIS
| Metric | Value |
|---------|-------|
| UI Elements | {total_elements} |
| Controls | {num_buttons} |
| Key Items | {button_list[:60]}{'...' if len(button_list) > 60 else ''} |

![Frame {idx}](annotated/{annotated_name})

### 📖 TRANSCRIPT ({ts_str})
> {transcript[:1000]}{'...' if len(transcript) > 1000 else ''}

### 💡 LEARNING
- **Context:** {context}
- **Action:** {action}

"""
        return md, section_id

    def get_transcript_segment(self, minutes: int, seconds: int, 
                               window: int = 45) -> str:
        """Extracts transcript segment near timestamp"""
        target_sec = minutes * 60 + seconds
        relevant = []
        
        for line in self.transcript_lines:
            match = re.match(r'^(\d+)m(\d+)s:\s*(.+)', line)
            if match:
                line_min = int(match.group(1))
                line_sec = int(match.group(2))
                line_time = line_min * 60 + line_sec
                text = match.group(3).strip()
                
                if abs(line_time - target_sec) <= window:
                    relevant.append(text)
            else:
                text = line.strip()
                if text and relevant:
                    relevant.append(text)
        
        return ' '.join(relevant) if relevant else "(No transcript in this interval)"

    def _infer_context(self, annotation: Optional[Dict], transcript: str) -> str:
        """Infers context based on annotation + transcript"""
        if not annotation:
            return "Visual analysis pending"
        
        keywords = {
            'modeling|blender|3d|mesh': '3D Modeling',
            'topology|edge|loop': 'Mesh Topology',
            'extrude|inset|bevel': 'Extrusion/Modification',
            'scale|rotate|transform|move': 'Transformation',
            'vertex|vertices|edge|face': 'Geometry Editing',
            'render|cycles|eevee': 'Rendering',
            'material|shader|texture|node': 'Materials/Shaders',
            'animation|keyframe|timeline|pose': 'Animation',
            'sculpt|brush|dynatopo': 'Sculpting',
            'uv|unwrap|seam|mapping': 'UV Mapping',
            'light|hdri|lamp|sun': 'Lighting',
            'camera|view|perspective': 'Camera/View',
            'modifier|array|mirror|subdivision': 'Modifiers',
            'rigging|armature|bone|weight': 'Rigging',
            'particle|hair|physics': 'Particles/Physics'
        }
        
        transcript_lower = transcript.lower()
        for pattern, desc in keywords.items():
            if any(k in transcript_lower for k in pattern.split('|')):
                return desc
        
        return "Tutorial in progress"
    
    def _infer_action(self, annotation: Optional[Dict], transcript: str) -> str:
        """Infers action being performed"""
        if not transcript or transcript.startswith("(No transcript"):
            return "Visual demonstration"
        
        transcript_lower = transcript.lower()
        
        action_patterns = [
            (['click', 'clique', 'select', 'selecione', 'choose'], "Selection/Click"),
            (['add', 'adicionar', 'create', 'criar', 'new', 'novo'], "Creation"),
            (['move', 'mover', 'drag', 'arrastar'], "Movement"),
            (['rotate', 'rotacionar', 'girar'], "Rotation"),
            (['scale', 'escalar', 'redimensionar'], "Scaling"),
            (['delete', 'deletar', 'remover', 'apagar'], "Deletion"),
            (['copy', 'copiar', 'duplicate', 'duplicar'], "Duplication"),
            (['press', 'pressione', 'key', 'shortcut', 'atalho'], "Keyboard Shortcut"),
            (['explain', 'explicar', 'show', 'mostrar', 'see'], "Explanation"),
            (['configure', 'configurar', 'adjust', 'ajustar', 'set'], "Configuration"),
        ]
        
        for words, action in action_patterns:
            if any(word in transcript_lower for word in words):
                return action
        
        return "Instruction/Demonstration"

    def _generate_executive_summary(self) -> str:
        """Generates executive summary"""
        total_elements = self.stats.get("total_elements", 0)
        annotated = self.stats.get("frames_annotated", 0)
        avg_elements = total_elements / annotated if annotated > 0 else 0
        
        contexts = set()
        for ann in self.annotations:
            if ann:
                ctx = self._infer_context(ann, "")
                if ctx != "Visual analysis pending":
                    contexts.add(ctx)
        
        duration = len(self.frame_paths) * self.interval
        
        return f"""
This document contains the automated analysis of **{len(self.frame_paths)} frames** extracted from the video, 
covering **{format_duration(duration)}** of content.

### 📊 Complexity Metrics
- **UI Elements per frame (avg):** {avg_elements:.1f}
- **Total elements detected:** {total_elements}
- **Annotation success rate:** {100*annotated/len(self.frame_paths) if self.frame_paths else 0:.1f}%

### 🎯 Identified Topics
{chr(10).join(f'- {ctx}' for ctx in sorted(contexts)) if contexts else '- General tutorial'}

### 📝 Transcript
- **Processed lines:** {len(self.transcript_lines)}
- **Language:** {self.language.upper()}
"""
